# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: brewery
      MONGO_INITDB_ROOT_PASSWORD: brewery
      MONGO_INITDB_DATABASE: breweries
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - brewery-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: brewery
      ME_CONFIG_MONGODB_ADMINPASSWORD: ci0tbootCamp
      ME_CONFIG_MONGODB_URL: mongodb://brewery:brewery@mongo:27017/
    networks:
      - brewery-network
networks:
  brewery-network:
    driver: bridge
volumes:
  mongodb_data: